trigger: 
  branches: 
    include: 
      - main    

variables:
  imageName: 'flask-app' # Name of the Docker image to build
  CLOUDSMITH_SERVICE: 'az-devops' # The service slug for the Cloudsmith service
  CLOUDSMITH_WORKSPACE: 'dmk-software-solutions' # The workspace identifier for Cloudsmith 
  CLOUDSMITH_REPOSITORY: 'qlik-webapp-dev' # The repository identifier for Cloudsmith 

stages:
  - stage: BuildAndPush
    jobs:
      - job: Build

        pool:
          vmImage: 'ubuntu-latest' 
        variables:
          - group: Secrets 
        steps:
          - checkout: self 

          - task: Docker@2 
            displayName: Login to Cloudsmith 
            inputs:
              command: login
              containerRegistry: cloudsmith-docker

          - task: Docker@2
            displayName: Build Docker image 
            inputs:
              command: build
              containerRegistry: cloudsmith-docker 
              repository: $(CLOUDSMITH_WORKSPACE)/$(CLOUDSMITH_REPOSITORY)/$(imageName) 
              Dockerfile: '**/Dockerfile'
              arguments: |
                --build-arg CLOUDSMITH_API_KEY=$(CLOUDSMITH_API_KEY) 
                --build-arg CLOUDSMITH_SERVICE=$(CLOUDSMITH_SERVICE)
                --build-arg CLOUDSMITH_WORKSPACE=$(CLOUDSMITH_WORKSPACE)
                --build-arg CLOUDSMITH_REPOSITORY=$(CLOUDSMITH_REPOSITORY)
              tags: |
                $(Build.BuildId)

          - task: Docker@2
            displayName: Push Docker image to Cloudsmith
            inputs:
              command: push
              repository: $(CLOUDSMITH_WORKSPACE)/$(CLOUDSMITH_REPOSITORY)/$(imageName)
              tags: |
                $(Build.BuildId)
