name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write # Necessary to use OIDC for authentication
  actions: write  # Necessary to cancel workflow executions
  contents: read  # Necessary to read the repository contents 

env:
  CLOUDSMITH_SERVICE: gh-actions-3vjo # The service slug for the Cloudsmith service
  CLOUDSMITH_WORKSPACE: red-acme-inc # The workspace slug for the Cloudsmith service 
  CLOUDSMITH_REPOSITORY: customer-dev # The repository slug for the Cloudsmith service

jobs:
  build-publish:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4

    - name: Auth to Cloudsmith with OIDC 
      uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2 
      with:
        oidc-namespace: ${{ env.CLOUDSMITH_WORKSPACE }}
        oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE }}
        oidc-auth-only: 'true' 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt --index-url https://$CLOUDSMITH_SERVICE:$CLOUDSMITH_API_KEY@dl.cloudsmith.io/basic/$CLOUDSMITH_WORKSPACE/$CLOUDSMITH_REPOSITORY/python/simple/
    
    - name: Test with pytest
      run: |
       pytest

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login to Cloudsmith
      uses: docker/login-action@v3
      with:
        registry: docker.cloudsmith.io
        username: ${{ env.CLOUDSMITH_SERVICE }}
        password: ${{ env.CLOUDSMITH_API_KEY }} 

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        provenance: false
        push: true
        tags: docker.cloudsmith.io/${{ env.CLOUDSMITH_WORKSPACE }}/${{ env.CLOUDSMITH_REPOSITORY }}/flask-app:${{github.run_number}}
        build-args: |
          CLOUDSMITH_SERVICE=${{ env.CLOUDSMITH_SERVICE }}
          CLOUDSMITH_WORKSPACE=${{ env.CLOUDSMITH_WORKSPACE }}
          CLOUDSMITH_REPOSITORY=${{ env.CLOUDSMITH_REPOSITORY }}
          CLOUDSMITH_API_KEY=${{ env.CLOUDSMITH_API_KEY }}
          BUILDKIT_PROGRESS=plain
